apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iot-gateway-service
  namespace: fms-iot-gateway
  labels:
    release: prometheus  # matches Prometheus Operator selector
spec:
  selector:
    matchLabels:
      app: iot-gateway-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
